app = 'nazwa-twojego-bota' # Możesz zmienić na unikalną nazwę
primary_region = 'waw' # 'waw' to Warszawa, dla niskich opóźnień

[build]
  builder = 'paketobuildpacks/builder:base'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1